# Generated by Django 2.2.1 on 2019-10-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_auto_20191016_1156'),
        ('dropdowndb', '0003_auto_20191016_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingStatus',
        ),
        migrations.DeleteModel(
            name='RequestStatus',
        ),
    ]
