# Generated by Django 2.2.1 on 2019-10-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowndb', '0005_bookingstatus_requeststatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptRejectBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARid', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=25)),
            ],
        ),
    ]
