# Generated by Django 2.2.1 on 2019-10-23 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowndb', '0006_acceptrejectbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptrejectbooking',
            name='ARid',
        ),
    ]
