# Generated by Django 2.2.1 on 2019-11-11 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowndb', '0008_statetax'),
        ('Booking', '0011_auto_20191030_1135'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenterFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.Booking')),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowndb.Rating')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
