# Generated by Django 2.2.1 on 2019-10-04 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='EndPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='StartPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowndb.Color'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowndb.Make'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowndb.Rating'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowndb.Style'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='zipcode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
