# Generated by Django 2.2.1 on 2019-10-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_auto_20191004_0412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-rating']},
        ),
        migrations.AddField(
            model_name='filter',
            name='bookingDate',
            field=models.DateField(null=True),
        ),
    ]
