# Generated by Django 2.2.1 on 2019-11-09 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dropdowndb', '0008_statetax'),
        ('Vehicle', '0003_auto_20191015_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowndb.Rating')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.Vehicle')),
            ],
        ),
    ]
