# Generated by Django 2.2.1 on 2019-10-16 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vehicle', '0003_auto_20191015_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateField()),
                ('bookingDoneOn', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('additionalDriverName', models.CharField(max_length=256, null=True)),
                ('additionalDriverLicense', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.Vehicle')),
            ],
        ),
    ]
