# Generated by Django 2.2.1 on 2019-10-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowndb', '0005_bookingstatus_requeststatus'),
        ('Booking', '0003_auto_20191016_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowndb.BookingStatus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='requestStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdowndb.RequestStatus'),
        ),
    ]
