# Generated by Django 2.2.1 on 2019-10-25 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_auto_20191016_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetailsCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank', models.CharField(max_length=256)),
                ('cardNumber', models.PositiveIntegerField()),
                ('cardCVV', models.PositiveIntegerField()),
                ('expDate', models.CharField(max_length=5)),
                ('zipCode', models.CharField(max_length=5)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetailsCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardHolderName', models.CharField(max_length=256)),
                ('cardNumber', models.PositiveIntegerField()),
                ('cardCVV', models.PositiveIntegerField()),
                ('expDate', models.CharField(max_length=5)),
                ('zipCode', models.CharField(max_length=5)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Booking')),
            ],
        ),
    ]
