# Generated by Django 2.2.1 on 2019-10-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_paymentdetailscard_paymentdetailscheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetailscheck',
            old_name='expDate',
            new_name='CheckDate',
        ),
        migrations.RenameField(
            model_name='paymentdetailscheck',
            old_name='cardCVV',
            new_name='CheckNumber',
        ),
        migrations.RenameField(
            model_name='paymentdetailscheck',
            old_name='cardNumber',
            new_name='RoutingNumber',
        ),
        migrations.RemoveField(
            model_name='paymentdetailscheck',
            name='zipCode',
        ),
    ]
