# Generated by Django 2.2.1 on 2019-10-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_auto_20191025_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetailsCheck',
        ),
    ]
