# Generated by Django 2.2.1 on 2019-10-25 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_delete_paymentdetailscheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetailsCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank', models.CharField(max_length=256)),
                ('CheckNumber', models.PositiveIntegerField()),
                ('RoutingNumber', models.PositiveIntegerField()),
                ('CheckDate', models.CharField(max_length=5)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Booking')),
            ],
        ),
    ]
